<?php
/**
 * FAQ Category URL Rewrite Observer
 *
 * @category  Panth
 * @package   Panth_Faq
 * @author    Panth
 * @copyright Copyright (c) 2025 Panth
 */
declare(strict_types=1);

namespace Panth\Faq\Observer;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use Magento\Store\Model\ScopeInterface;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollectionFactory;
use Magento\UrlRewrite\Model\UrlRewriteFactory;
use Panth\Faq\Model\ResourceModel\Category as CategoryResource;
use Psr\Log\LoggerInterface;

class CategoryUrlRewriteObserver implements ObserverInterface
{
    const ENTITY_TYPE = 'faq_category';

    /**
     * @var UrlRewriteFactory
     */
    protected $urlRewriteFactory;

    /**
     * @var UrlRewriteCollectionFactory
     */
    protected $urlRewriteCollectionFactory;

    /**
     * @var StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var LoggerInterface
     */
    protected $logger;

    /**
     * @var ScopeConfigInterface
     */
    protected $scopeConfig;

    /**
     * @var CategoryResource
     */
    protected $categoryResource;

    public function __construct(
        UrlRewriteFactory $urlRewriteFactory,
        UrlRewriteCollectionFactory $urlRewriteCollectionFactory,
        StoreManagerInterface $storeManager,
        LoggerInterface $logger,
        ScopeConfigInterface $scopeConfig,
        CategoryResource $categoryResource
    ) {
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->urlRewriteCollectionFactory = $urlRewriteCollectionFactory;
        $this->storeManager = $storeManager;
        $this->logger = $logger;
        $this->scopeConfig = $scopeConfig;
        $this->categoryResource = $categoryResource;
    }

    public function execute(Observer $observer)
    {
        try {
            $category = $observer->getEvent()->getCategory();
            if (!$category || !$category->getId() || !$category->getUrlKey()) {
                return;
            }

            $categoryId = (int)$category->getId();

            // Read default url_key from the main table (see Item observer
            // for the rationale).
            $defaults = $this->categoryResource->loadDefaultValuesPublic($categoryId);
            $defaultUrlKey = (string)($defaults['url_key'] ?? $category->getUrlKey());
            if ($defaultUrlKey === '') {
                return;
            }

            $this->deleteExistingRewrites($categoryId);

            $stores = $category->getStores() ?: $category->getData('store_id') ?: [0];
            if (!is_array($stores)) {
                $stores = [$stores];
            }

            foreach ($stores as $storeId) {
                $storeId = (int)$storeId;
                $slug = $defaultUrlKey;
                if ($storeId > 0) {
                    $override = $this->categoryResource->getStoreOverrideRow($categoryId, $storeId);
                    if (!empty($override['url_key'])) {
                        $slug = (string)$override['url_key'];
                    }
                }
                $this->createUrlRewrite($categoryId, $slug, $storeId);
            }
        } catch (\Throwable $e) {
            $this->logger->error('FAQ Category URL Rewrite Error: ' . $e->getMessage());
        }
    }

    protected function deleteExistingRewrites(int $categoryId): void
    {
        $collection = $this->urlRewriteCollectionFactory->create();
        $collection->addFieldToFilter('entity_type', self::ENTITY_TYPE)
            ->addFieldToFilter('entity_id', $categoryId);

        foreach ($collection as $urlRewrite) {
            try {
                $urlRewrite->delete();
            } catch (\Throwable $e) {
                $this->logger->error('Error deleting URL rewrite: ' . $e->getMessage());
            }
        }
    }

    protected function createUrlRewrite(int $categoryId, string $slug, int $storeId): void
    {
        $faqUrlKey = $this->scopeConfig->getValue(
            'panth_faq/general/faq_route',
            ScopeInterface::SCOPE_STORE,
            $storeId
        );
        if (!$faqUrlKey) {
            $faqUrlKey = 'faq';
        }
        $faqUrlKey = trim((string)$faqUrlKey, '/');

        $urlRewrite = $this->urlRewriteFactory->create();
        $urlRewrite->setEntityType(self::ENTITY_TYPE)
            ->setEntityId($categoryId)
            ->setRequestPath($faqUrlKey . '/category/' . $slug)
            ->setTargetPath('faq/category/view/id/' . $categoryId)
            ->setStoreId($storeId)
            ->setIsAutogenerated(1);

        try {
            $urlRewrite->save();
        } catch (\Throwable $e) {
            $this->logger->error('Error creating URL rewrite: ' . $e->getMessage());
        }
    }
}
