<?php
/**
 * FAQ Category URL Rewrite Observer
 *
 * @category  Panth
 * @package   Panth_Faq
 * @author    Panth
 * @copyright Copyright (c) 2025 Panth
 */
declare(strict_types=1);

namespace Panth\Faq\Observer;

use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use Magento\UrlRewrite\Model\UrlRewriteFactory;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollectionFactory;
use Magento\Store\Model\StoreManagerInterface;
use Psr\Log\LoggerInterface;

class CategoryUrlRewriteObserver implements ObserverInterface
{
    const ENTITY_TYPE = 'faq_category';

    /**
     * @var UrlRewriteFactory
     */
    protected $urlRewriteFactory;

    /**
     * @var UrlRewriteCollectionFactory
     */
    protected $urlRewriteCollectionFactory;

    /**
     * @var StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var LoggerInterface
     */
    protected $logger;

    /**
     * @param UrlRewriteFactory $urlRewriteFactory
     * @param UrlRewriteCollectionFactory $urlRewriteCollectionFactory
     * @param StoreManagerInterface $storeManager
     * @param LoggerInterface $logger
     */
    public function __construct(
        UrlRewriteFactory $urlRewriteFactory,
        UrlRewriteCollectionFactory $urlRewriteCollectionFactory,
        StoreManagerInterface $storeManager,
        LoggerInterface $logger
    ) {
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->urlRewriteCollectionFactory = $urlRewriteCollectionFactory;
        $this->storeManager = $storeManager;
        $this->logger = $logger;
    }

    /**
     * Generate URL rewrites for FAQ category
     *
     * @param Observer $observer
     * @return void
     */
    public function execute(Observer $observer)
    {
        try {
            $category = $observer->getEvent()->getCategory();

            if (!$category || !$category->getId() || !$category->getUrlKey()) {
                return;
            }

            // Delete existing URL rewrites for this category
            $this->deleteExistingRewrites($category->getId());

            // Get stores
            $stores = $category->getStores() ?: $category->getData('store_id') ?: [0];
            if (!is_array($stores)) {
                $stores = [$stores];
            }

            foreach ($stores as $storeId) {
                $this->createUrlRewrite($category, (int)$storeId);
            }
        } catch (\Exception $e) {
            $this->logger->error('FAQ Category URL Rewrite Error: ' . $e->getMessage());
        }
    }

    /**
     * Delete existing URL rewrites
     *
     * @param int $categoryId
     * @return void
     */
    protected function deleteExistingRewrites($categoryId)
    {
        $collection = $this->urlRewriteCollectionFactory->create();
        $collection->addFieldToFilter('entity_type', self::ENTITY_TYPE)
            ->addFieldToFilter('entity_id', $categoryId);

        foreach ($collection as $urlRewrite) {
            try {
                $urlRewrite->delete();
            } catch (\Exception $e) {
                $this->logger->error('Error deleting URL rewrite: ' . $e->getMessage());
            }
        }
    }

    /**
     * Create URL rewrite
     *
     * @param \Panth\Faq\Model\Category $category
     * @param int $storeId
     * @return void
     */
    protected function createUrlRewrite($category, $storeId)
    {
        $urlRewrite = $this->urlRewriteFactory->create();
        $urlRewrite->setEntityType(self::ENTITY_TYPE)
            ->setEntityId($category->getId())
            ->setRequestPath('faq/category/' . $category->getUrlKey())
            ->setTargetPath('faq/category/view/id/' . $category->getId())
            ->setStoreId($storeId)
            ->setIsAutogenerated(1);

        try {
            $urlRewrite->save();
        } catch (\Exception $e) {
            $this->logger->error('Error creating URL rewrite: ' . $e->getMessage());
        }
    }
}
