<?php
/**
 * FAQ Item URL Rewrite Observer
 *
 * @category  Panth
 * @package   Panth_Faq
 * @author    Panth
 * @copyright Copyright (c) 2025 Panth
 */
declare(strict_types=1);

namespace Panth\Faq\Observer;

use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use Magento\UrlRewrite\Model\UrlRewriteFactory;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollectionFactory;
use Magento\Store\Model\StoreManagerInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Store\Model\ScopeInterface;
use Psr\Log\LoggerInterface;

class ItemUrlRewriteObserver implements ObserverInterface
{
    const ENTITY_TYPE = 'faq_item';

    /**
     * @var UrlRewriteFactory
     */
    protected $urlRewriteFactory;

    /**
     * @var UrlRewriteCollectionFactory
     */
    protected $urlRewriteCollectionFactory;

    /**
     * @var StoreManagerInterface
     */
    protected $storeManager;

    /**
     * @var ScopeConfigInterface
     */
    protected $scopeConfig;

    /**
     * @var LoggerInterface
     */
    protected $logger;

    /**
     * @param UrlRewriteFactory $urlRewriteFactory
     * @param UrlRewriteCollectionFactory $urlRewriteCollectionFactory
     * @param StoreManagerInterface $storeManager
     * @param ScopeConfigInterface $scopeConfig
     * @param LoggerInterface $logger
     */
    public function __construct(
        UrlRewriteFactory $urlRewriteFactory,
        UrlRewriteCollectionFactory $urlRewriteCollectionFactory,
        StoreManagerInterface $storeManager,
        ScopeConfigInterface $scopeConfig,
        LoggerInterface $logger
    ) {
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->urlRewriteCollectionFactory = $urlRewriteCollectionFactory;
        $this->storeManager = $storeManager;
        $this->scopeConfig = $scopeConfig;
        $this->logger = $logger;
    }

    /**
     * Generate URL rewrites for FAQ item
     *
     * @param Observer $observer
     * @return void
     */
    public function execute(Observer $observer)
    {
        try {
            $item = $observer->getEvent()->getItem();

            if (!$item || !$item->getId() || !$item->getUrlKey()) {
                return;
            }

            // Delete existing URL rewrites for this item
            $this->deleteExistingRewrites($item->getId());

            // Get stores
            $stores = $item->getStores() ?: $item->getData('store_id') ?: [0];
            if (!is_array($stores)) {
                $stores = [$stores];
            }

            foreach ($stores as $storeId) {
                $this->createUrlRewrite($item, (int)$storeId);
            }
        } catch (\Exception $e) {
            $this->logger->error('FAQ Item URL Rewrite Error: ' . $e->getMessage());
        }
    }

    /**
     * Delete existing URL rewrites
     *
     * @param int $itemId
     * @return void
     */
    protected function deleteExistingRewrites($itemId)
    {
        $collection = $this->urlRewriteCollectionFactory->create();
        $collection->addFieldToFilter('entity_type', self::ENTITY_TYPE)
            ->addFieldToFilter('entity_id', $itemId);

        foreach ($collection as $urlRewrite) {
            try {
                $urlRewrite->delete();
            } catch (\Exception $e) {
                $this->logger->error('Error deleting URL rewrite: ' . $e->getMessage());
            }
        }
    }

    /**
     * Create URL rewrite
     *
     * @param \Panth\Faq\Model\Item $item
     * @param int $storeId
     * @return void
     */
    protected function createUrlRewrite($item, $storeId)
    {
        // Get configured FAQ URL key
        $faqUrlKey = $this->scopeConfig->getValue(
            'panth_faq/general/url_key',
            ScopeInterface::SCOPE_STORE,
            $storeId
        );

        if (!$faqUrlKey) {
            $faqUrlKey = 'faq';
        }

        $faqUrlKey = trim($faqUrlKey, '/');

        $urlRewrite = $this->urlRewriteFactory->create();
        $urlRewrite->setEntityType(self::ENTITY_TYPE)
            ->setEntityId($item->getId())
            ->setRequestPath($faqUrlKey . '/item/' . $item->getUrlKey())
            ->setTargetPath('faq/index/view/id/' . $item->getId())
            ->setStoreId($storeId)
            ->setIsAutogenerated(1);

        try {
            $urlRewrite->save();
        } catch (\Exception $e) {
            $this->logger->error('Error creating URL rewrite: ' . $e->getMessage());
        }
    }
}
