<?php
declare(strict_types=1);

namespace Panth\Faq\Observer;

use Magento\Framework\Event\Observer;
use Magento\Framework\Event\ObserverInterface;
use Magento\UrlRewrite\Model\UrlRewriteFactory;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollectionFactory;
use Magento\Store\Model\StoreManagerInterface;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Store\Model\ScopeInterface;
use Panth\Faq\Model\ResourceModel\Item as ItemResource;
use Psr\Log\LoggerInterface;

class ItemUrlRewriteObserver implements ObserverInterface
{
    const ENTITY_TYPE = 'faq_item';

    protected $urlRewriteFactory;

    protected $urlRewriteCollectionFactory;

    protected $storeManager;

    protected $scopeConfig;

    protected $logger;

    protected $itemResource;

    public function __construct(
        UrlRewriteFactory $urlRewriteFactory,
        UrlRewriteCollectionFactory $urlRewriteCollectionFactory,
        StoreManagerInterface $storeManager,
        ScopeConfigInterface $scopeConfig,
        LoggerInterface $logger,
        ItemResource $itemResource
    ) {
        $this->urlRewriteFactory = $urlRewriteFactory;
        $this->urlRewriteCollectionFactory = $urlRewriteCollectionFactory;
        $this->storeManager = $storeManager;
        $this->scopeConfig = $scopeConfig;
        $this->logger = $logger;
        $this->itemResource = $itemResource;
    }

    public function execute(Observer $observer)
    {
        try {
            $item = $observer->getEvent()->getItem();

            if (!$item || !$item->getId() || !$item->getUrlKey()) {
                return;
            }

            $itemId = (int)$item->getId();

            $defaults = $this->itemResource->loadDefaultValuesPublic($itemId);
            $defaultUrlKey = (string)($defaults['url_key'] ?? $item->getUrlKey());
            if ($defaultUrlKey === '') {
                return;
            }

            $this->deleteExistingRewrites($itemId);

            $stores = $item->getStores() ?: $item->getData('store_id') ?: [0];
            if (!is_array($stores)) {
                $stores = [$stores];
            }

            foreach ($stores as $storeId) {
                $storeId = (int)$storeId;
                $slug = $defaultUrlKey;
                if ($storeId > 0) {
                    $override = $this->itemResource->getStoreOverrideRow($itemId, $storeId);
                    if (!empty($override['url_key'])) {
                        $slug = (string)$override['url_key'];
                    }
                }
                $this->createUrlRewrite($itemId, $slug, $storeId);
            }
        } catch (\Throwable $e) {
            $this->logger->error('FAQ Item URL Rewrite Error: ' . $e->getMessage());
        }
    }

    protected function deleteExistingRewrites($itemId)
    {
        $collection = $this->urlRewriteCollectionFactory->create();
        $collection->addFieldToFilter('entity_type', self::ENTITY_TYPE)
            ->addFieldToFilter('entity_id', $itemId);

        foreach ($collection as $urlRewrite) {
            try {
                $urlRewrite->delete();
            } catch (\Exception $e) {
                $this->logger->error('Error deleting URL rewrite: ' . $e->getMessage());
            }
        }
    }

    protected function createUrlRewrite(int $itemId, string $slug, int $storeId): void
    {
        $faqUrlKey = $this->scopeConfig->getValue(
            'panth_faq/general/faq_route',
            ScopeInterface::SCOPE_STORE,
            $storeId
        );
        if (!$faqUrlKey) {
            $faqUrlKey = 'faq';
        }
        $faqUrlKey = trim((string)$faqUrlKey, '/');

        $urlRewrite = $this->urlRewriteFactory->create();
        $urlRewrite->setEntityType(self::ENTITY_TYPE)
            ->setEntityId($itemId)
            ->setRequestPath($faqUrlKey . '/item/' . $slug)
            ->setTargetPath('faq/index/view/id/' . $itemId)
            ->setStoreId($storeId)
            ->setIsAutogenerated(1);

        try {
            $urlRewrite->save();
        } catch (\Throwable $e) {
            $this->logger->error('Error creating URL rewrite: ' . $e->getMessage());
        }
    }
}
