<?php
declare(strict_types=1);

namespace Panth\Faq\Test\Unit\Observer;

use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\DataObject;
use Magento\Framework\Event;
use Magento\Framework\Event\Observer;
use Magento\Store\Model\StoreManagerInterface;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollection;
use Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollectionFactory;
use Magento\UrlRewrite\Model\UrlRewrite;
use Magento\UrlRewrite\Model\UrlRewriteFactory;
use Panth\Faq\Model\ResourceModel\Category as CategoryResource;
use Panth\Faq\Observer\CategoryUrlRewriteObserver;
use Psr\Log\LoggerInterface;
use PHPUnit\Framework\TestCase;

class CategoryUrlRewriteObserverTest extends TestCase
{
    protected array $created = [];
    protected array $existing = [];
    protected array $filters = [];
    protected array $defaults = [];
    protected array $overrides = [];
    protected array $routes = [];
    protected bool $saveFails = false;
    protected array $logged = [];

    protected function eventKey(): string
    {
        return 'category';
    }

    protected function entityType(): string
    {
        return 'faq_category';
    }

    protected function pathSegment(): string
    {
        return 'category';
    }

    protected function targetPath(int $id): string
    {
        return 'faq/category/view/id/' . $id;
    }

    protected function resourceClass(): string
    {
        return CategoryResource::class;
    }

    protected function buildObserver(...$args): object
    {
        return new CategoryUrlRewriteObserver($args[0], $args[1], $args[2], $args[3], $args[4], $args[5]);
    }

    protected function observer(): object
    {
        $factory = $this->createStub(UrlRewriteFactory::class);
        $factory->method('create')->willReturnCallback(function () {
            $rewrite = new class ($this) extends UrlRewrite {
                public function __construct(private $test)
                {
                }

                public function save()
                {
                    $this->test->recordSave($this);
                    return $this;
                }
            };
            return $rewrite;
        });
        $collection = $this->createStub(UrlRewriteCollection::class);
        $collection->method('addFieldToFilter')->willReturnCallback(function ($field, $value) use ($collection) {
            $this->filters[] = [$field, $value];
            return $collection;
        });
        $collection->method('getIterator')->willReturnCallback(fn () => new \ArrayIterator($this->existing));
        $collectionFactory = $this->createStub(UrlRewriteCollectionFactory::class);
        $collectionFactory->method('create')->willReturn($collection);

        $config = $this->createStub(ScopeConfigInterface::class);
        $config->method('getValue')->willReturnCallback(
            fn ($path, $scope = null, $store = null) => $this->routes[(int)$store] ?? null
        );
        $resource = $this->createStub($this->resourceClass());
        $resource->method('loadDefaultValuesPublic')->willReturnCallback(fn () => $this->defaults);
        $resource->method('getStoreOverrideRow')->willReturnCallback(
            fn ($id, $storeId) => $this->overrides[$storeId] ?? []
        );
        $logger = $this->createStub(LoggerInterface::class);
        $logger->method('error')->willReturnCallback(function ($message) {
            $this->logged[] = $message;
        });
        $storeManager = $this->createStub(StoreManagerInterface::class);

        return $this->buildObserver($factory, $collectionFactory, $storeManager, $logger, $config, $resource);
    }

    public function recordSave(UrlRewrite $rewrite): void
    {
        if ($this->saveFails) {
            throw new \RuntimeException('duplicate request path');
        }
        $this->created[] = [
            'entity_type' => $rewrite->getEntityType(),
            'entity_id' => $rewrite->getEntityId(),
            'request_path' => $rewrite->getRequestPath(),
            'target_path' => $rewrite->getTargetPath(),
            'store_id' => $rewrite->getStoreId(),
            'is_autogenerated' => $rewrite->getIsAutogenerated(),
        ];
    }

    protected function dispatch($entity): void
    {
        $event = new Event([$this->eventKey() => $entity]);
        $this->observer()->execute(new Observer(['event' => $event]));
    }

    public function testIgnoresMissingEntityOrUrlKey(): void
    {
        $this->dispatch(null);
        $this->dispatch(new DataObject(['id' => 0, 'url_key' => 'x']));
        $this->dispatch(new DataObject(['id' => 3, 'url_key' => '']));

        $this->assertSame([], $this->created);
        $this->assertSame([], $this->filters);
    }

    public function testEmptyDefaultUrlKeySkipsRewrite(): void
    {
        $this->defaults = ['url_key' => ''];

        $this->dispatch(new DataObject(['id' => 3, 'url_key' => 'scoped']));

        $this->assertSame([], $this->created);
        $this->assertSame([], $this->filters);
    }

    public function testReplacesRewritesForEveryStoreUsingOverrides(): void
    {
        $old = $this->createMock(UrlRewrite::class);
        $old->expects($this->once())->method('delete');
        $broken = $this->createStub(UrlRewrite::class);
        $broken->method('delete')->willThrowException(new \RuntimeException('locked row'));
        $this->existing = [$old, $broken];
        $this->defaults = ['url_key' => 'default-key'];
        $this->overrides = [2 => ['url_key' => 'store-two-key'], 3 => ['url_key' => null]];
        $this->routes = [2 => '/help/'];

        $this->dispatch(new DataObject(['id' => '7', 'url_key' => 'scoped', 'stores' => ['0', '2', '3']]));

        $this->assertSame([['entity_type', $this->entityType()], ['entity_id', 7]], $this->filters);
        $this->assertSame(['Error deleting URL rewrite: locked row'], $this->logged);
        $segment = $this->pathSegment();
        $this->assertSame(
            [
                ['faq/' . $segment . '/default-key', 0],
                ['help/' . $segment . '/store-two-key', 2],
                ['faq/' . $segment . '/default-key', 3],
            ],
            array_map(static fn ($r) => [$r['request_path'], $r['store_id']], $this->created)
        );
        foreach ($this->created as $rewrite) {
            $this->assertSame($this->entityType(), $rewrite['entity_type']);
            $this->assertSame(7, $rewrite['entity_id']);
            $this->assertSame($this->targetPath(7), $rewrite['target_path']);
            $this->assertSame(1, $rewrite['is_autogenerated']);
        }
    }

    public function testFallsBackToEntityUrlKeyAndStoreIdData(): void
    {
        $this->dispatch(new DataObject(['id' => 5, 'url_key' => 'own-key', 'store_id' => '4']));

        $this->assertCount(1, $this->created);
        $this->assertSame('faq/' . $this->pathSegment() . '/own-key', $this->created[0]['request_path']);
        $this->assertSame(4, $this->created[0]['store_id']);
    }

    public function testDefaultsToAdminStoreWhenNoStoresAssigned(): void
    {
        $this->dispatch(new DataObject(['id' => 5, 'url_key' => 'own-key']));

        $this->assertSame(0, $this->created[0]['store_id']);
    }

    public function testSaveFailureIsLogged(): void
    {
        $this->saveFails = true;

        $this->dispatch(new DataObject(['id' => 5, 'url_key' => 'own-key']));

        $this->assertSame([], $this->created);
        $this->assertSame(['Error creating URL rewrite: duplicate request path'], $this->logged);
    }
}
